# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-11 23:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_distancematrix_api_key', models.CharField(help_text='Chave da api google distancematrix', max_length=255, verbose_name='Chave (DistanceMatrix)')),
                ('latitude', models.CharField(help_text='Latitude do endereço da sua casa', max_length=255, verbose_name='Latitude')),
                ('longitude', models.CharField(help_text='Longitude do endereço da sua casa', max_length=255, verbose_name='Longitude')),
            ],
        ),
    ]
