# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-12 00:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracao',
            name='habilitar',
            field=models.BooleanField(default=False, help_text='Habilita ou desabilita a configuração', verbose_name='Habilitar/Desabilitar'),
        ),
    ]
