# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-12 00:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_configuracao_habilitar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuracao',
            options={'verbose_name_plural': 'Configurações'},
        ),
        migrations.RemoveField(
            model_name='configuracao',
            name='habilitar',
        ),
        migrations.AddField(
            model_name='configuracao',
            name='habilitado',
            field=models.BooleanField(default=False, help_text='Habilita ou desabilita a configuração', verbose_name='Habilitado'),
        ),
    ]
