# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-12 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20170912_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localizacao',
            name='datahora',
            field=models.DateTimeField(auto_now=True, help_text='Data e Hora da última localização', verbose_name='Data/Hora'),
        ),
    ]
