# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20170912_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracao',
            name='google_maps_api_key',
            field=models.CharField(default=1, help_text='Chave da api google maps', max_length=255, verbose_name='Chave (Maps)'),
            preserve_default=False,
        ),
    ]
