# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_configuracao_google_maps_api_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracao',
            name='google_distancematrix_api_key',
        ),
        migrations.AlterField(
            model_name='configuracao',
            name='google_maps_api_key',
            field=models.CharField(help_text='Chave da api google maps', max_length=255, verbose_name='Chave (API Maps)'),
        ),
    ]
