# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20170921_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='foto',
            field=models.ImageField(default='user.jpg', help_text='Foto do usuário', upload_to='', verbose_name='Foto'),
        ),
    ]
